baseURL = 'https://example.org/'
locale = 'en-US'
title = 'archwiki theme'

[menus]
  [[menus.main]]
    name = 'bio'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'projects'
    pageRef = '/projects'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
